steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=image-builder-enc.key
  - --plaintext-file=image-builder.key
  - --location=global
  - --keyring=packer
  - --key=pk
- name: 'gcr.io/$PROJECT_ID/packer'
  args:
  - build
  - -var
  - project_id=$PROJECT_ID
  - -var
  - machine_type=${_MACHINE_TYPE}
  - -var
  - zone=${_ZONE}
  - -var
  - source_image=${_SOURCE_IMAGE}
  - -var
  - source_image_project_id=${_SOURCE_IMAGE_PROJECT_ID}
  - packer.pkr.hcl
substitutions:
  _MACHINE_TYPE: c2-standard-60
  _SOURCE_IMAGE: rocky-linux-8-v20220317
  _SOURCE_IMAGE_PROJECT_ID: rocky-linux-cloud 
tags: ['cloud-builders-community']
timeout: 10800s
